server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: rag
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
#  mvc:
#    static-path-pattern: /static/**

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret

  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        initialize-schema: true
    openai:
      api-key: ${OPENAI_API_KEY}


#docker run -it --rm --name postgres -h postgres -p 5433:5433 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres pgvector/pgvector