server:
  port: 7002

springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method

spring:
  application:
    name=chat
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Spring_Chatting
    username: root
    password: 1234
  jpa:
    show-sql: true

token:
  secret-key: "SECRET"
  refresh-secret-key: "REFRESH_SECRET"
  token-time: 300
  refresh-token-time: 300
